-- drop objects if exists
DROP TABLE IF exists  songs;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE songs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    "songName" varchar NOT NULL,
    artist varchar NOT NULL,
    album varchar NOT NULL,
    writers varchar NOT NULL,
    "releaseYear" int4 NOT NULL,
    "createdAt" timestamp NOT NULL DEFAULT now(),
    "updatedAt" timestamp NOT NULL DEFAULT now()
);


INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('The 1', 'Taylor Swift', 'Taylor Swift, Aaron Dessner', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('22', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Afterglow', 'Taylor Swift', 'Taylor Swift, Louis Bell, Frank Dukes', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('All Too Well', 'Taylor Swift', 'Taylor Swift, Liz Rose', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('All You Had to Do Was Stay', 'Taylor Swift', 'Taylor Swift, Max Martin', '1989', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('American Girl (cover)', 'Taylor Swift', 'Tom Petty', 'None[a]', '2009');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('The Archer', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('August', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Babe', 'Sugarland featuring Taylor Swift', 'Taylor Swift, Patrick Monahan', 'Bigger', '2018');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Back to December', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Bad Blood (album version)', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', '1989', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Bad Blood (remixed single version)', 'Taylor Swift featuring Kendrick Lamar', 'Taylor Swift, Max Martin, Shellback, Kendrick Lamar', 'None[b]', '2015');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Beautiful Eyes', 'Taylor Swift', 'Taylor Swift', 'Beautiful Eyes', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Beautiful Ghosts', 'Taylor Swift', 'Taylor Swift, Andrew Lloyd Webber', 'Cats: Highlights from the Motion Picture Soundtrack', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Begin Again', 'Taylor Swift', 'Taylor Swift', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('The Best Day', 'Taylor Swift', 'Taylor Swift', 'Fearless', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Bette Davis Eyes (live cover)', 'Taylor Swift', 'Donna Weiss, Jackie DeShannon', 'Speak Now World Tour – Live', '2011');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Better than Revenge', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Betty', 'Taylor Swift', 'Taylor Swift, William Bowery', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Big Star (Live)', 'Kenny Chesney, and Taylor Swift', 'Stephony Smith', 'Live in No Shoes Nation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Blank Space', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', '1989', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Both of Us', 'B.o.B featuring Taylor Swift', 'Bobby Ray Simmons, Jr., Taylor Swift, Ammar Malik, Lukasz Gottwald, Henry Walter', 'Strange Clouds', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Breathe', 'Taylor Swift featuring Colbie Caillat', 'Taylor Swift, Colbie Caillat', 'Fearless', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Breathless (cover)', 'Taylor Swift', 'Kevin Griffin', 'Hope for Haiti Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Call It What You Want', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Cardigan', 'Taylor Swift', 'Taylor Swift, Aaron Dessner', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Change', 'Taylor Swift', 'Taylor Swift', 'AT&T Team USA Soundtrack and Fearless', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Christmas Must Be Something More', 'Taylor Swift', 'Taylor Swift', 'Sounds of the Season', '2007');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Christmas Tree Farm', 'Taylor Swift', 'Taylor Swift', 'None', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Christmases When You Were Mine', 'Taylor Swift', 'Taylor Swift, Liz Rose, Nathan Chapman', 'Sounds of the Season', '2007');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Clean', 'Taylor Swift', 'Taylor Swift, Imogen Heap', '1989', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Cold as You', 'Taylor Swift', 'Taylor Swift, Liz Rose', 'Taylor Swift', '2006');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Come Back... Be Here', 'Taylor Swift', 'Taylor Swift, Dan Wilson', 'Red, (Deluxe edition)', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Come in with the Rain', 'Taylor Swift', 'Taylor Swift, Liz Rose', 'Fearless, (Platinum edition)', '2009');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Cornelia Street', 'Taylor Swift', 'Taylor Swift', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Crazier', 'Taylor Swift', 'Taylor Swift, Robert Ellis Orrall', 'Hannah Montana: The Movie', '2009');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Cruel Summer', 'Taylor Swift', 'Taylor Swift, Jack Antonoff, St. Vincent', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Dancing with Our Hands Tied', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback, Oscar Holter', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Daylight', 'Taylor Swift', 'Taylor Swift', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Death by a Thousand Cuts', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Dear John', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Delicate', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Don''t Blame Me', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Dress', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Drops of Jupiter (live cover)', 'Taylor Swift', 'Charlie Colin, Rob Hotchkiss, Jimmy Stafford, Pat Monahan, Scott Underwood', 'Speak Now World Tour – Live', '2011');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Enchanted', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('End Game', 'Taylor Swift featuring Ed Sheeran and Future', 'Taylor Swift, Max Martin, Shellback, Ed Sheeran, Nayvadius Wilburn', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Epiphany', 'Taylor Swift', 'Taylor Swift, Aaron Dessner', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Everything Has Changed', 'Taylor Swift featuring Ed Sheeran', 'Taylor Swift, Ed Sheeran', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Exile', 'Taylor Swift featuring Bon Iver', 'Taylor Swift, Justin Vernon, William Bowery', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Eyes Open', 'Taylor Swift', 'Taylor Swift', 'The Hunger Games', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('False God', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Fearless', 'Taylor Swift', 'Taylor Swift, Liz Rose, Hillary Lindsey', 'Fearless', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Fifteen', 'Taylor Swift', 'Taylor Swift', 'Fearless', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Forever & Always', 'Taylor Swift', 'Taylor Swift', 'Fearless', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Forever & Always (piano version)', 'Taylor Swift', 'Taylor Swift', 'Fearless, (Platinum edition)', '2009');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Getaway Car', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Girl at Home', 'Taylor Swift', 'Taylor Swift', 'Red, (Deluxe edition)', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Gorgeous', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Half of My Heart (album version)', 'John Mayer featuring Taylor Swift', 'John Mayer', 'Battle Studies', '2009');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Haunted', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Hey Stephen', 'Taylor Swift', 'Taylor Swift', 'Fearless', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Highway Don''t Care', 'Tim McGraw and Taylor Swift featuring Keith Urban', 'Mark Irwin, Josh Kear, Brad Warren, Brett Warren', 'Two Lanes of Freedom', '2013');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Hoax', 'Taylor Swift', 'Taylor Swift, Aaron Dessner', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Hold On (live cover)', 'Jack Ingram featuring Taylor Swift', 'Blu Sanders', 'Rhapsody Originals[c]', '2007');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Holy Ground', 'Taylor Swift', 'Taylor Swift', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('How You Get the Girl', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', '1989', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('I Almost Do', 'Taylor Swift', 'Taylor Swift', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('I Did Something Bad', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('I Don''t Wanna Live Forever', 'Zayn and Taylor Swift', 'Taylor Swift, Sam Dew, Jack Antonoff', 'Fifty Shades Darker: Original Motion Picture Soundtrack', '2016');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('I Forgot That You Existed', 'Taylor Swift', 'Taylor Swift, Louis Bell, Frank Dukes', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('I Heart ?', 'Taylor Swift', 'Taylor Swift', 'Beautiful Eyes', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('I Knew You Were Trouble', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('I Know Places', 'Taylor Swift', 'Taylor Swift, Ryan Tedder', '1989', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('I Think He Knows', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('I Want You Back (live cover)', 'Taylor Swift', 'Freddie Perren, Deke Richards, Berry Gordy, Jr., Alphonso Mizell', 'Speak Now World Tour – Live', '2011');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('I Wish You Would', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', '1989', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('If This Was a Movie', 'Taylor Swift', 'Taylor Swift, Martin Johnson', 'Speak Now, (Deluxe edition)', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Illicit Affairs', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Innocent', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Invisible', 'Taylor Swift', 'Taylor Swift, Robert Ellis Orrall', 'Taylor Swift, (Deluxe edition)', '2007');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Invisible String', 'Taylor Swift', 'Taylor Swift, Aaron Dessner', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('It''s Nice to Have a Friend', 'Taylor Swift', 'Taylor Swift, Louis Bell, Frank Dukes', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('I''d Lie', 'Taylor Swift', 'Taylor Swift', 'None', '2006');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('I''m Only Me When I''m with You', 'Taylor Swift', 'Taylor Swift, Robert Ellis Orrall, Angelo Petraglia', 'Taylor Swift, (Deluxe edition)', '2007');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Jump Then Fall', 'Taylor Swift', 'Taylor Swift', 'Fearless, (Platinum edition) and Valentine''s Day: Soundtrack', '2009');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('King of My Heart', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('The Lakes', 'Taylor Swift', 'TBA', 'Folklore, (Physical Edition)', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Last Christmas (cover)', 'Taylor Swift', 'George Michael', 'Sounds of the Season', '2007');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('The Last Great American Dynasty', 'Taylor Swift', 'Taylor Swift, Aaron Dessner', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Last Kiss', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('The Last Time', 'Taylor Swift featuring Gary Lightbody of Snow Patrol', 'Taylor Swift, Gary Lightbody, Jacknife Lee', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Long Live', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Long Live (single version)', 'Taylor Swift featuring Paula Fernandes', 'Taylor Swift, Paula Fernandes', 'Speak Now World Tour – Live', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('London Boy', 'Taylor Swift', 'Taylor Swift, Jack Antonoff, Cautious Clay, Sounwave', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Look What You Made Me Do', 'Taylor Swift', 'Taylor Swift, Jack Antonoff, Fred Fairbrass, Richard Fairbrass, Rob Manzoli[d]', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Love Story', 'Taylor Swift', 'Taylor Swift', 'Fearless', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Lover', 'Taylor Swift', 'Taylor Swift', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Lover (Remix)', 'Taylor Swift featuring Shawn Mendes', 'Taylor Swift, Shawn Mendes, Scott Harris', 'None[e]', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('The Lucky One', 'Taylor Swift', 'Taylor Swift', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Macavity (cover)', 'Taylor Swift, and Idris Elba', 'Andrew Lloyd Webber, T. S. Eliot', 'Cats: Highlights from the Motion Picture Soundtrack', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Mad Woman', 'Taylor Swift', 'Taylor Swift, Aaron Dessner', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('The Man', 'Taylor Swift', 'Taylor Swift, Joel Little', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Mary''s Song (Oh My My My)', 'Taylor Swift', 'Taylor Swift, Liz Rose, Brian Maher', 'Taylor Swift', '2006');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Me!', 'Taylor Swift featuring Brendon Urie of Panic! at the Disco', 'Taylor Swift, Joel Little, Brendon Urie', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Mean', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Mine', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Mirrorball', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Miss Americana & the Heartbreak Prince', 'Taylor Swift', 'Taylor Swift, Joel Little', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('The Moment I Knew', 'Taylor Swift', 'Taylor Swift', 'Red, (Deluxe edition)', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('My Tears Ricochet', 'Taylor Swift', 'Taylor Swift', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Never Grow Up', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('New Romantics', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', '1989, (Deluxe edition)', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('New Year''s Day', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Only the Young', 'Taylor Swift', 'Taylor Swift, Joel Little', 'None', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('The Other Side of the Door', 'Taylor Swift', 'Taylor Swift', 'Fearless, (Platinum edition)', '2009');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Our Song', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', '2006');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Ours', 'Taylor Swift', 'Taylor Swift', 'Speak Now, (Deluxe edition)', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Out of the Woods', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', '1989', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('The Outside', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', '2006');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Paper Rings', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Peace', 'Taylor Swift', 'Taylor Swift, Aaron Dessner', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('A Perfectly Good Heart', 'Taylor Swift', 'Taylor Swift, Brett James, Troy Verges', 'Taylor Swift, (Deluxe edition)', '2007');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Picture to Burn', 'Taylor Swift', 'Taylor Swift, Liz Rose', 'Taylor Swift', '2006');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('A Place in This World', 'Taylor Swift', 'Taylor Swift, Robert Ellis Orrall, Angelo Petraglia', 'Taylor Swift', '2006');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('...Ready for It?', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback, Ali Payami', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Red', 'Taylor Swift', 'Taylor Swift', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Ronan', 'Taylor Swift', 'Taylor Swift, Maya Thompson', 'None', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Sad Beautiful Tragic', 'Taylor Swift', 'Taylor Swift', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Safe & Sound', 'Taylor Swift featuring The Civil Wars', 'Taylor Swift, Joy Williams, John Paul White, T-Bone Burnett', 'The Hunger Games', '2011');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Santa Baby (cover)', 'Taylor Swift', 'Joan Javits, Philip Springer, Tony Springer', 'Sounds of the Season', '2007');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('September (cover)', 'Taylor Swift', 'Maurice White, Al McKay, Allee Willis', 'Spotify Singles', '2018');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Seven', 'Taylor Swift', 'Taylor Swift, Aaron Dessner', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Shake It Off', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', '1989', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Should''ve Said No', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', '2006');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Silent Night (cover)', 'Taylor Swift', 'Josef Mohr, Franz Xaver Gruber', 'Sounds of the Season', '2007');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('So It Goes...', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback, Oscar Görres', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Soon You''ll Get Better', 'Taylor Swift featuring Dixie Chicks', 'Taylor Swift, Jack Antonoff', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Sparks Fly', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Speak Now', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Starlight', 'Taylor Swift', 'Taylor Swift', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('State of Grace', 'Taylor Swift', 'Taylor Swift', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Stay Beautiful', 'Taylor Swift', 'Taylor Swift, Liz Rose', 'Taylor Swift', '2006');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Stay Stay Stay', 'Taylor Swift', 'Taylor Swift', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('The Story of Us', 'Taylor Swift', 'Taylor Swift', 'Speak Now', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Style', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback, Ali Payami', '1989', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Superman', 'Taylor Swift', 'Taylor Swift', 'Speak Now, (Deluxe edition)', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Superstar', 'Taylor Swift', 'Taylor Swift', 'Fearless, (Platinum edition)', '2009');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Sweeter than Fiction', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'One Chance Soundtrack', '2013');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Teardrops on My Guitar', 'Taylor Swift', 'Taylor Swift, Liz Rose', 'Taylor Swift', '2006');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Tell Me Why', 'Taylor Swift', 'Taylor Swift, Liz Rose', 'Fearless', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('This Is Me Trying', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Folklore', '2020');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('This Is Why We Can''t Have Nice Things', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', 'Reputation', '2017');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('This Love', 'Taylor Swift', 'Taylor Swift', '1989', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Tied Together with a Smile', 'Taylor Swift', 'Taylor Swift, Liz Rose', 'Taylor Swift', '2006');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Tim McGraw', 'Taylor Swift', 'Taylor Swift, Liz Rose', 'Taylor Swift', '2006');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Today Was a Fairytale', 'Taylor Swift', 'Taylor Swift', 'Valentine''s Day[f]', '2010');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Treacherous', 'Taylor Swift', 'Taylor Swift, Dan Wilson', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Two Is Better Than One', 'Boys Like Girls featuring Taylor Swift', 'Martin Johnson, Taylor Swift', 'Love Drunk', '2009');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Umbrella (live cover)', 'Taylor Swift', 'Christopher Tricky Stewart, Terius Dream Nash, Thaddis Harrell, Shawn Carter', 'iTunes Live from SoHo', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Untouchable', 'Taylor Swift', 'Cary Barlowe, Nathan Barlowe, Tommy Lee James, Taylor Swift[g]', 'Fearless, (Platinum edition)', '2009');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('The Way I Loved You', 'Taylor Swift', 'Taylor Swift, John Rich', 'Fearless', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('We Are Never Ever Getting Back Together', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', 'Red', '2012');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Welcome to New York', 'Taylor Swift', 'Taylor Swift, Ryan Tedder', '1989', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('White Christmas (cover)', 'Taylor Swift', 'Irving Berlin', 'Sounds of the Season', '2007');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('White Horse', 'Taylor Swift', 'Taylor Swift, Liz Rose', 'Fearless', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Wildest Dreams', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', '1989', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('Wonderland', 'Taylor Swift', 'Taylor Swift, Max Martin, Shellback', '1989, (Deluxe edition)', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('You Are in Love', 'Taylor Swift', 'Taylor Swift, Jack Antonoff', '1989, (Deluxe edition)', '2014');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('You Belong with Me', 'Taylor Swift', 'Taylor Swift, Liz Rose', 'Fearless', '2008');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('You Need to Calm Down', 'Taylor Swift', 'Taylor Swift, Joel Little', 'Lover', '2019');
INSERT INTO songs ("songName", artist,  writers, album, "releaseYear") VALUES ('You''re Not Sorry', 'Taylor Swift', 'Taylor Swift', 'Fearless', '2008');